name: Send the list of PRs awaiting review to Teams
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # 4.2.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Send reminder
        uses: ./.github/actions/send-prs-to-teams
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
